<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38856" started-at="2022-04-29T20:27:48 IST" finished-at="2022-04-29T20:28:27 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38856" started-at="2022-04-29T20:27:48 IST" finished-at="2022-04-29T20:28:27 IST">
      <class name="test.Tests">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:test.Tests@2bbf4b8b]" name="launchBrowser" is-config="true" duration-ms="18719" started-at="2022-04-29T20:27:48 IST" finished-at="2022-04-29T20:28:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="signUpWithFillingInformation()[pri:0, instance:test.Tests@2bbf4b8b]" name="signUpWithFillingInformation" duration-ms="1330" started-at="2022-04-29T20:28:07 IST" finished-at="2022-04-29T20:28:08 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at test.Tests.signUpWithFillingInformation(Tests.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpWithFillingInformation -->
        <test-method status="PASS" signature="failedScreenShots(org.testng.ITestResult)[pri:0, instance:test.Tests@2bbf4b8b]" name="failedScreenShots" is-config="true" duration-ms="563" started-at="2022-04-29T20:28:08 IST" finished-at="2022-04-29T20:28:09 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=signUpWithFillingInformation status=FAILURE method=Tests.signUpWithFillingInformation()[pri:0, instance:test.Tests@2bbf4b8b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedScreenShots -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:test.Tests@2bbf4b8b]" name="launchBrowser" is-config="true" duration-ms="17781" started-at="2022-04-29T20:28:09 IST" finished-at="2022-04-29T20:28:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="validateEnglish_Dutch_Present()[pri:0, instance:test.Tests@2bbf4b8b]" name="validateEnglish_Dutch_Present" duration-ms="143" started-at="2022-04-29T20:28:27 IST" finished-at="2022-04-29T20:28:27 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Dutc] but found [Dutch]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Dutc] but found [Dutch]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.Tests.validateEnglish_Dutch_Present(Tests.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEnglish_Dutch_Present -->
        <test-method status="PASS" signature="failedScreenShots(org.testng.ITestResult)[pri:0, instance:test.Tests@2bbf4b8b]" name="failedScreenShots" is-config="true" duration-ms="269" started-at="2022-04-29T20:28:27 IST" finished-at="2022-04-29T20:28:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateEnglish_Dutch_Present status=FAILURE method=Tests.validateEnglish_Dutch_Present()[pri:0, instance:test.Tests@2bbf4b8b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedScreenShots -->
      </class> <!-- test.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
